MarkdownManager/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MarkdownManager.Models;
using PagedList;
using Microsoft.AspNet.Identity;

namespace MarkdownManager.Controllers
{
    public class DocumentController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Document
        public ActionResult Index(string sortParentFolderOrder, string sortNameOrder, string currentFilter, string searchString, int? page)
        {
            // Sorting Criteria
            ViewBag.CurrentNameSort = sortNameOrder;
            ViewBag.CurrentParentFolderSort = sortParentFolderOrder;
            ViewBag.NameSortParam = sortNameOrder == "name_asc" ? "name_desc" : "name_asc";
            ViewBag.ParentFolderSortParam = sortParentFolderOrder == "parentfolder_asc" ? "parentfolder_desc" : "parentfolder_asc";

            // Pagination and persistent filtering
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            // Find documents that belong to the user
            var documents = from d in db.Documents select d;
            string currentUser = User.Identity.GetUserId();

            documents = documents.Where(doc => doc.ApplicationUserID == currentUser);
            documents = documents.Where(doc => doc.ApplicationUserID == currentUser).OrderBy(d => d.ParentFolder);

            if (!String.IsNullOrEmpty(searchString))
            {
                documents = documents.Where(doc => doc.ApplicationUserID == currentUser);
                documents = documents.Where(doc => doc.ParentFolder.Contains(searchString));
            }

            // Order the found documents as specified
            switch (sortNameOrder)
            {
                case "name_desc":
                    documents = documents.Where(doc => doc.ApplicationUserID == currentUser).OrderByDescending(d => d.Name);
                    break;
                case "name_asc":
                    documents = documents.Where(doc => doc.ApplicationUserID == currentUser).OrderBy(d => d.Name);
                    break;
            }

            switch (sortParentFolderOrder)
            {
                case "parentfolder_desc":
                    documents = documents.Where(doc => doc.ApplicationUserID == currentUser).OrderByDescending(d => d.ParentFolder);
                    break;
                case "parentfolder_asc":
                    documents = documents.Where(doc => doc.ApplicationUserID == currentUser).OrderBy(d => d.ParentFolder);
                    break;
            }

            // Specify the pagination settings and render view
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(documents.ToPagedList(pageNumber, pageSize));
        }

        
        // GET: Document/Details/5
        // This route is not currently being accessed, it seems unnecessary in the current version
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }


        // GET: Document/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Document/Create
        // Route adjusted so upon creation, redirect to the edit of that note/document
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Text,ParentFolder")] Document document)
        {
            string currentUser = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                document.ApplicationUserID = currentUser;
                db.Documents.Add(document);
                db.SaveChanges();
                var id = db.Documents.Find(document.Id).Id;
                return RedirectToAction("Edit", new { id = id });
            }
            return View(document);
        }


        // GET: Document/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Document/Edit/5
        // Route adjusted to provide a "success" message upon saving the document. Will keep the document open
        //  so the user can save as they work (and not be redirected to the index)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Text,ParentFolder")] Document document)
        {
            string currentUser = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(document).State = EntityState.Modified;
                document.ApplicationUserID = currentUser;
                db.SaveChanges();
                ViewData["message"] = "Note Saved!";
                return View();
            }
            return View(document);
        }


        // GET: Document/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index");
        }

        // POST: Document/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = db.Documents.Find(id);
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // Dispose of the database connection
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MarkdownManager/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MarkdownManager.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System.Web.Services;
using System.Data.SqlClient;
using PagedList;

namespace MarkdownManager.Controllers
{

    
    [Authorize]
    public class ToDoController : Controller
    {
        private ApplicationDbContext db;
        private UserManager<MyUser> manager;

        public ToDoController()
        {
            db = new ApplicationDbContext();
            manager = new UserManager<MyUser>(new UserStore<MyUser>(db));
        }




        // GET: ToDo
        public ActionResult Index(string sortTagOrder, string sortDescOrder, string sortDoneOrder, string currentFilter, string searchString, int? page)
        {
            // Sort Order Criteria
            ViewBag.CurrentDescSort = sortDescOrder;
            ViewBag.CurrentDoneSort = sortDoneOrder;
            ViewBag.CurrentTagSort = sortTagOrder;
            ViewBag.DescriptionSortParam = sortDescOrder == "description_asc" ? "description_desc" : "description_asc";
            ViewBag.IsDoneSortParam = sortDoneOrder == "isDone_asc" ? "isDone_desc" : "isDone_asc";
            ViewBag.TagSortParam = sortTagOrder == "tag_asc" ? "tag_desc" : "tag_asc";

            // Pagination and persistent filtering
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            // Find ToDos that belong to the user
            var todoes = from t in db.ToDoes select t;
            string currentUser = User.Identity.GetUserId();

            todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser);
            todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderBy(t => t.Tag);

            if (!String.IsNullOrEmpty(searchString))
            {
                todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser);
                todoes = todoes.Where(todo => todo.Tag.Contains(searchString));
            }

            // Order the ToDos as specified
            switch (sortDescOrder)
            {
                case "description_desc":
                    todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderByDescending(t => t.Description);
                    break;
                case "description_asc":
                    todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderBy(t => t.Description);
                    break;

            }

            switch(sortDoneOrder)
            {
                case "isDone_desc":
                    todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderByDescending(t => t.IsDone ? 0 : 1);
                    break;
                case "isDone_asc":
                    todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderBy(t => t.IsDone ? 0 : 1);
                    break;

            }
                
            switch(sortTagOrder)
            {
                case "tag_desc":
                    todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderByDescending(t => t.Tag);
                    break;
                case "tag_asc":
                    todoes = todoes.Where(todo => todo.ApplicationUserID == currentUser).OrderBy(t => t.Tag);
                    break;
            }
                
        

            // Pagination settings and render the view
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(todoes.ToPagedList(pageNumber, pageSize));
        }


        // GET: ToDo/Details/5
        // This route is not currently being accessed, it seems unnecessary in the current version
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDoes.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }


        // GET: ToDo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToDo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,IsDone,Tag")] ToDo toDo)
        {
            string currentUser = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                toDo.ApplicationUserID = currentUser;
                db.ToDoes.Add(toDo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(toDo);
        }


        // GET: ToDo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDoes.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return View(toDo);
        }
        
        // POST: ToDo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,IsDone,Tag")] ToDo toDo)
        {
            string currentUser = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                db.Entry(toDo).State = EntityState.Modified;
                toDo.ApplicationUserID = currentUser;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDo);

        }


        // GET: ToDo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDoes.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index");
        }

        // POST: ToDo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ToDo toDo = db.ToDoes.Find(id);
            db.ToDoes.Remove(toDo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // Dispose of the database connection
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MarkdownManager/Views/Shared/View.cshtml
@model MarkdownManager.Models.ToDo

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text-center">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="container" style="padding: 0; margin-bottom:5px;">
            <div class="col-md-5">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @id = "todoDesc", @placeholder = "Description", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-5">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @id = "todoTag", @placeholder = "Tag", @data_url = @Url.Action("Create", "ToDo"), @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-2">
                <input id="addTodo" type="button" value="Create ToDo" class="btn btn-default" style="width: 100%;" />
            </div>
        </div>
    </div>
} 


<script>
    $('#addTodo').click(function () {
        //alert("button clicked");
        var tag = $('#todoTag').val();
        var desc = $('#todoDesc').val();
        var isDone = false;
        var url = $('#todoTag').data('url');
        //alert(tag + desc + isDone);

        var form = $('#__AjaxAntiForgeryForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();
        $.ajax({
            url: url,
            type: 'POST',
            data: {
                __RequestVerificationToken: token,
                IsDone: isDone,
                Description: desc,
                Tag: tag
            },
            success: function (result) {
                alert("Todo Successful Updated");
                // clear the boxes out
                $('#todoTag').val("");
                $('#todoDesc').val("");
            },
            error: function (err) {
                console.log("submit error");
            }
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MarkdownManager/Views/Shared/_AddToDoPartial.cshtml
@model MarkdownManager.Models.ToDo

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text-center">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="container no-gutter" style="padding: 0; margin-bottom:5px;">
            <div class="col-xs-5 col-md-5">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @id = "todoDesc", @placeholder = "Description", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>

            <div class="col-xs-4 col-md-5">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @id = "todoTag", @placeholder = "Tag", @data_url = @Url.Action("Create", "ToDo"), @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>

            <div class="col-xs-3 col-md-2">
                <input id="addTodo" type="button" value="Create ToDo" class="btn btn-default" style="width: 100%;" />
            </div>
        </div>
    </div>
} 


<script>
    $('#addTodo').click(function () {
        // alert("button clicked");
        var tag = $('#todoTag').val();
        var desc = $('#todoDesc').val();
        var isDone = false;
        var url = $('#todoTag').data('url');
        // alert(tag + desc + isDone);

        var form = $('#__AjaxAntiForgeryForm');
        var token = $('input[name="__RequestVerificationToken"]', form).val();
        $.ajax({
            url: url,
            type: 'POST',
            data: {
                __RequestVerificationToken: token,
                IsDone: isDone,
                Description: desc,
                Tag: tag
            },
            success: function (result) {
                alert("Todo Successful Updated");
                // clear the boxes out
                $('#todoTag').val("");
                $('#todoDesc').val("");
                // If on the ToDo path, refresh page
                var pathname = window.location.pathname;
                if (pathname.toLocaleLowerCase() == "/todo") {
                    $('#searchStringBtn').click();
                }
            },
            error: function (err) {
                console.log("submit error");
            }
        });
    });
</script>


@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
}

MarkdownManager/Views/Shared/_CreateNotePartial.cshtml
@model MarkdownManager.Models.Document

<!-- Form Control (CRUD - Create) -->
@using (Html.BeginForm("Create", "Document"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="margin: 20px 0 0 0;">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="container" style="padding: 0; margin-bottom:10px;">
            <div class="text-center no-gutter">
                <div class="col-xs-5 col-md-5">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @placeholder = "Note Name", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4 col-md-5">
                    @Html.EditorFor(model => model.ParentFolder, new { htmlAttributes = new { @placeholder = "Tag", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ParentFolder, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-3 col-md-2">
                    <input type="submit" value="Create" class="btn btn-primary" style="width: 100%;" />
                </div>

                <div id="markdown-input" class="" style="display:none;">
                    @Html.TextArea(" ", new { @id = "markdown-text", @class = "source full-height form-control" })
                </div>

            </div>
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
}

MarkdownManager/Views/Shared/_CreateToDoPartial.cshtml
@model MarkdownManager.Models.ToDo


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUserID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MarkdownManager/Views/Shared/_HeaderDemo.cshtml
@{
    var title = (string)ViewData["title"];
}

<div id="headerDemo"class="row no-gutter">
    <div class="col-xs-12 col-md-4">
        <h2>@title</h2>
        <h6><em>Markdown Conversion Powered By <a href="https://github.com/jonschlinkert/remarkable">Jon Schlinkert - Remarkable</a></em></h6>
        <h6><em>Syntax Highlighting Powered By <a href="https://highlightjs.org/">Highlight.js</a></em></h6>
    </div>
    <div class="col-xs-12 col-md-8 text-right" style="padding-top: 30px;">
        <label class="checkbox-inline">
            <input id="markdown-view" type="checkbox" checked data-toggle="toggle">Markdown
        </label>
        <label class="checkbox-inline">
            <input id="html-view" type="checkbox" checked data-toggle="toggle">HTML
        </label>
        <label class="checkbox-inline">
            <input id="jsfiddle" type="checkbox" data-toggle="toggle">JSFiddle
        </label>
    </div>
</div>
<hr />

MarkdownManager/Views/Shared/_HeaderWTogglesPartial.cshtml
@{
    var title = (string)ViewData["title"];
    var message = (string)ViewData["message"];
}

<div class="row no-gutter">
    <div class="col-xs-12 col-md-4">
        <h2>@title: <p id="hideMe" style="display:inline; color:deeppink;">@message</p> </h2>
        <h6><em>Markdown Conversion Powered By <a href="https://github.com/jonschlinkert/remarkable">Jon Schlinkert - Remarkable</a></em></h6>
        <h6><em>Syntax Highlighting Powered By <a href="https://highlightjs.org/">Highlight.js</a></em></h6>
    </div>
    <div class="col-xs-12 col-md-8 text-right" style="padding-top: 30px;">
        @Html.ActionLink("Back to List", "Index", null, new { @style = "margin-right:10px;", @class = "btn btn-default" })
        <label class="checkbox-inline">
            <input id="markdown-view" type="checkbox" checked data-toggle="toggle">Markdown
        </label>
        <label class="checkbox-inline">
            <input id="html-view" type="checkbox" checked data-toggle="toggle">HTML
        </label>
        <label class="checkbox-inline">
            <input id="easy-todo" type="checkbox" checked data-toggle="toggle">ToDo
        </label>
        <label class="checkbox-inline">
            <input id="jsfiddle" type="checkbox" data-toggle="toggle">JSFiddle
        </label>
    </div>
</div>
<hr />

MarkdownManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Markdown Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Markdown Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Notes", "Index", "Document")</li>
                    <li>@Html.ActionLink("ToDo", "Index", "ToDo")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Markdown Manager</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MarkdownManager/Views/Shared/_MarkdownContainersWModel.cshtml
@model MarkdownManager.Models.Document

<div class="container full-height form-control">
    <div class="row full-height">
        <div id="markdown-input" class="col-md-6 full-height">
            <div id="markdown-buttons" class="demo-control"><a href="#" class="source-clear">clear</a><a id="permalink" href="./" title="Share this snippet as link"><strong>permalink</strong></a></div>
            @Html.TextAreaFor(model => model.Text, new { @id = "markdown-text", @class = "source full-height form-control" })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
        <!-- output panel -->
        <section id="html-output" class="col-md-6 full-height">
            <div id="html-buttons" class="demo-control"><a href="#" data-result-as="html">html</a><a href="#" data-result-as="src">source</a></div>
            <div class="result-html full-height"></div>
            <pre class="result-src full-height"><code class="result-src-content full-height"></code></pre>
            @*<pre><code><div class="result-src full-height"><div class="result-src-content full-height"></div></div></code></pre>*@
            @*<pre class="result-debug full-height"><code class="result-debug-content full-height"></code></pre>*@
        </section>
    </div>
</div>

MarkdownManager/Views/Shared/_MarkdownDemo.cshtml


<div class="container full-height form-control">
    <div class="row full-height">
        <div id="markdown-input" class="col-md-6 full-height">
            <div id="markdown-buttons" class="demo-control"><a href="#" class="source-clear">clear</a><a id="permalink" href="./" title="Share this snippet as link"><strong>permalink</strong></a></div>
            <textarea id="markdown-text" class="source full-height form-control">
<p align="center"><img src="/Images/Logo.png"></p>

# Welcome to Markdown Manager
**Markdown Manager** is a web based markdown editor with a focus on management through notes and todos.

Play around with this *Live Demo* to see the power and ease of using Markdown for note taking.

Let me help you get started:

# Header -> `# Header`
You can use one to six # to control the header size

**Bold** -> `**Bold**` and *Italic* -> `*Italic*`

Looking for Order or Unordered lists?
* Simple! -> `* Simple!`
* Nested, yeah! -> `  * Nested, yeah!`
1. Number one -> `1. Number one`

`Inline code` with backticks

```
# code block
print '3 backticks or'
print 'indent 4 spaces'
console.log("cat");
```    
            </textarea>

        </div>
        <!-- output panel -->
        <section id="html-output" class="col-md-6 full-height">
            <div id="html-buttons" class="demo-control"><a href="#" data-result-as="html">html</a><a href="#" data-result-as="src">source</a></div>
            <div class="result-html full-height"></div>
            <pre class="result-src full-height"><code class="result-src-content full-height"></code></pre>
            <pre class="result-debug full-height"><code class="result-debug-content full-height"></code></pre>
        </section>
    </div>
</div>